### ISSUE TITLE
Saving with a Subsystem widget fails

### ISSUE THREAD

**Issue by LTCNugget** [wpilibsuite/SmartDashboard#100]
When saving a layout with a `edu.wpi.first.smartdashboard.gui.elements.Subsystem` widget, SmartDashboard crashes with a `NullPointerException`. The resulting save file is blank.
Relevant stack trace:
~~~
Saving to:      C:\Users\%USER%\SmartDashboard\save.xml
Feb 21, 2018 10:10:31 AM edu.wpi.first.smartdashboard.gui.DashboardFrame save
SEVERE: null
java.lang.NullPointerException
        at edu.wpi.first.smartdashboard.gui.DashboardFrame.saveElements(DashboardFrame.java:283)
        at edu.wpi.first.smartdashboard.gui.DashboardFrame.save(DashboardFrame.java:259)
        at edu.wpi.first.smartdashboard.gui.DashboardFrame.exit(DashboardFrame.java:416)
        at edu.wpi.first.smartdashboard.gui.DashboardFrame$2.windowClosing(DashboardFrame.java:180)
        at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
        at java.awt.Window.processWindowEvent(Unknown Source)
        at javax.swing.JFrame.processWindowEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
~~~

**Comment by LTCNugget** [comment]
After looking through the SmartDashboard code, it seems the problem was that I wasn't setting the type attribute (a requirement for Widgets) for my Subsystem widget in the XML file. If I am not mistaken, widgets are used when the value can be set by the user, otherwise the classes extend StaticWidget. It doesn't seem that the value for a Subsystem widget can be changed from the dashboard, so why isn't it a static widget?

**Comment by LTCNugget** [comment]
After further looking into the code, it appears I was mistaken.
